#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source ${OPENSHIFT_REPO_DIR}conf/app.conf
cd ${OPENSHIFT_DATA_DIR}tomcat
sed -ig 's/OPENSHIFT_INTERNAL_IP/'$OPENSHIFT_DIY_IP'/g' conf/server.xml
# Download latest nexus
rm -Rf webapps/*
wget $nexus_war_url -O webapps/ROOT.war