#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -x
if [ -d $OPENSHIFT_DATA_DIR/tomcat ]
then
    exit 0
else
	mkdir $OPENSHIFT_DATA_DIR/prefs
    cp -rf $OPENSHIFT_REPO_DIR/diy/tomcat $OPENSHIFT_DATA_DIR
    cd $OPENSHIFT_DATA_DIR/tomcat
    rm -rf logs
    ln -s $OPENSHIFT_DIY_LOG_DIR logs
    sed -ig 's/OPENSHIFT_APP_DNS/'$OPENSHIFT_APP_DNS'/' conf/server.xml
fi
